User-delete-entry - Heerak Moon
heerakmoon/code-journal-0123 pull request #8
Opened 2023-02-22 11:17 UTC by heerakmoon

https://user-images.githubusercontent.com/113075380/220604945-372dbab1-a2ac-42c7-891c-b686d89a3e17.mp4

2023-02-22 13:00 UTC, robgmerrill requested changes
One last request! Because I didn't see local storage in the submission video I couldn't see if `data.nextEntryId` is being reduced by 1 for each deleted item. If it is, please send me a gif. If not, I commented in the file where I think you can make that update. Slack me any questions if that isn't clear!

2023-02-22 13:00 UTC, robgmerrill commented on js/main.js
> +  data.editing = null;
One last thing. I didn't see your local storage in the submission video but I'm guessing that `data.nextEntryId` isn't being lowered by one every time an item is being deleted. To do that you would just decrement the value by one when the confirm button is clicked.

`data.nextEntryId--`

2023-02-23 07:07 UTC, heerakmoon commented
https://user-images.githubusercontent.com/113075380/220840202-bb84932b-51e6-4ba6-9340-bb31af81bf70.mp4

2023-02-23 12:45 UTC, robgmerrill approved these changes
👍

2023-03-01 22:12 UTC, merged